name: mdns-browser
base: core24
version: "0.8.14"
summary: mDNS-Browser app
description: |
  A cross platform mDNS-Browser app written in Rust using tauri and leptos
grade: stable
confinement: strict
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  mdns-browser:
    command: usr/bin/mdns-browser
    desktop: usr/share/applications/mdns-browser.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - x11
      - wayland

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .
    override-build: |
      set -eu
      rustup toolchain install stable --target wasm32-unknown-unknown --profile minimal --no-self-update
      cargo --locked install trunk --version ^0.21.1
      cargo --locked install tauri-cli --version ^2.0.3
      cargo --locked install cargo-auditable
      cargo --locked auditable tauri build -b deb
      dpkg -x target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
      sed -i -e "s|Icon=mdns-browser|Icon=/usr/share/icons/hicolor/32x32/apps/mdns-browser.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/mdns-browser.desktop
