name: mdns-browser
base: core24
version: "0.9.0"
summary: mDNS-Browser app
description: |
  A cross platform mDNS-Browser app written in Rust using tauri and leptos
grade: stable
confinement: strict
icon: src-tauri/icons/icon.png
issues: https://github.com/hrzlgnm/mdns-browser/issues
license: MIT License
source-code: https://github.com/hrzlgnm/mdns-browser

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  mdns-browser:
    command: usr/bin/mdns-browser
    desktop: usr/share/applications/mdns-browser.desktop
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - x11
      - wayland

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: https://github.com/hrzlgnm/mdns-browser/releases/download/mdns-browser-v0.9.0/mdns-browser_0.9.0_amd64.deb
    source-type: deb
    override-build: |
      snapcraftctl build
      sed -i -e "s|Icon=mdns-browser|Icon=/usr/share/icons/hicolor/32x32/apps/mdns-browser.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/mdns-browser.desktop
