
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.addr2line]]
version = "0.24.1"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-deploy"

[[exemptions.alloc-stdlib]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.android-tzdata]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.android_log-sys]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.android_logger]]
version = "0.14.1"
criteria = "safe-to-deploy"

[[exemptions.approx]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.arboard]]
version = "3.4.1"
criteria = "safe-to-deploy"

[[exemptions.async-recursion]]
version = "1.1.1"
criteria = "safe-to-deploy"

[[exemptions.attribute-derive]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.attribute-derive-macro]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.block]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.block2]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.borsh]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.borsh-derive]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.brotli]]
version = "6.0.0"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "4.0.1"
criteria = "safe-to-deploy"

[[exemptions.byte-unit]]
version = "5.1.4"
criteria = "safe-to-deploy"

[[exemptions.bytecheck]]
version = "0.6.12"
criteria = "safe-to-deploy"

[[exemptions.bytecheck_derive]]
version = "0.6.12"
criteria = "safe-to-deploy"

[[exemptions.byteorder-lite]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.cairo-sys-rs]]
version = "0.18.2"
criteria = "safe-to-deploy"

[[exemptions.camino]]
version = "1.1.9"
criteria = "safe-to-deploy"

[[exemptions.cargo_toml]]
version = "0.17.2"
criteria = "safe-to-deploy"

[[exemptions.cesu8]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.cfb]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.ciborium]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-io]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.ciborium-ll]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.clipboard-win]]
version = "5.4.0"
criteria = "safe-to-deploy"

[[exemptions.cocoa]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.cocoa-foundation]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.collection_literals]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.combine]]
version = "4.6.7"
criteria = "safe-to-deploy"

[[exemptions.console_log]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.33"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.33"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.core-foundation-sys]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.core-graphics]]
version = "0.23.2"
criteria = "safe-to-deploy"

[[exemptions.core-graphics]]
version = "0.24.0"
criteria = "safe-to-deploy"

[[exemptions.core-graphics-types]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.14"
criteria = "safe-to-deploy"

[[exemptions.ctor]]
version = "0.2.8"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.10"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.10"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.10"
criteria = "safe-to-deploy"

[[exemptions.dashmap]]
version = "5.5.3"
criteria = "safe-to-deploy"

[[exemptions.derive-where]]
version = "1.2.7"
criteria = "safe-to-deploy"

[[exemptions.derive_more]]
version = "0.99.18"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.dispatch]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.dlopen2]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.dlopen2_derive]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.dpi]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.drain_filter_polyfill]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.dtoa-short]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.dunce]]
version = "1.0.5"
criteria = "safe-to-deploy"

[[exemptions.embed-resource]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.embed_plist]]
version = "1.2.2"
criteria = "safe-to-deploy"

[[exemptions.error-code]]
version = "3.3.1"
criteria = "safe-to-deploy"

[[exemptions.fast-srgb8]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.field-offset]]
version = "0.3.6"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futf]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.gdk-pixbuf-sys]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.gethostname]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.1.16"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.15"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.0"
criteria = "safe-to-deploy"

[[exemptions.gio-sys]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.glib-sys]]
version = "0.18.1"
criteria = "safe-to-deploy"

[[exemptions.gloo-net]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.gloo-utils]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.gobject-sys]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.half]]
version = "2.4.1"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.html-escape]]
version = "0.2.13"
criteria = "safe-to-deploy"

[[exemptions.html5ever]]
version = "0.26.0"
criteria = "safe-to-deploy"

[[exemptions.ico]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.if-addrs]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.image]]
version = "0.25.2"
criteria = "safe-to-deploy"

[[exemptions.infer]]
version = "0.16.0"
criteria = "safe-to-deploy"

[[exemptions.instant]]
version = "0.1.13"
criteria = "safe-to-deploy"

[[exemptions.interpolator]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.ipnet]]
version = "2.10.0"
criteria = "safe-to-deploy"

[[exemptions.is-docker]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.is-wsl]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.itertools]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.jni-sys]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.jpeg-decoder]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.json-patch]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.jsonptr]]
version = "0.4.7"
criteria = "safe-to-deploy"

[[exemptions.keyboard-types]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.kuchikiki]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.leptos]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_config]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_dom]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_hot_reload]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_macro]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_meta]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_reactive]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.leptos_server]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.7.4"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.mac]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.manyhow]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.manyhow-macros]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.markup5ever]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.memoffset]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.minimal-lexical]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.ndk]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.ndk-sys]]
version = "0.6.0+11769913"
criteria = "safe-to-deploy"

[[exemptions.nodrop]]
version = "0.1.14"
criteria = "safe-to-deploy"

[[exemptions.num_enum]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.num_enum_derive]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.num_threads]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.objc]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.objc-sys]]
version = "0.3.5"
criteria = "safe-to-deploy"

[[exemptions.objc2]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-app-kit]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-core-data]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-core-image]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-encode]]
version = "4.0.3"
criteria = "safe-to-deploy"

[[exemptions.objc2-foundation]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-metal]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.objc2-quartz-core]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.4"
criteria = "safe-to-deploy"

[[exemptions.oco_ref]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.20.1"
criteria = "safe-to-deploy"

[[exemptions.open]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.option-ext]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.pad-adapter]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.palette]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.palette_derive]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.pango-sys]]
version = "0.18.0"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_codegen]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_generator]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_macros]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.plist]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-crate]]
version = "2.0.2"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-utils]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-utils]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2-diagnostics]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.ptr_meta_derive]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.quick-xml]]
version = "0.32.0"
criteria = "safe-to-deploy"

[[exemptions.quote-use]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.quote-use-macros]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.rand_hc]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.rand_pcg]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.raw-window-handle]]
version = "0.6.2"
criteria = "safe-to-deploy"

[[exemptions.rend]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.rkyv]]
version = "0.7.45"
criteria = "safe-to-deploy"

[[exemptions.rkyv_derive]]
version = "0.7.45"
criteria = "safe-to-deploy"

[[exemptions.rstml]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.rust_decimal]]
version = "1.36.0"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.21"
criteria = "safe-to-deploy"

[[exemptions.seahash]]
version = "4.1.0"
criteria = "safe-to-deploy"

[[exemptions.self_cell]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.send_wrapper]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.serde-wasm-bindgen]]
version = "0.6.5"
criteria = "safe-to-deploy"

[[exemptions.serde_qs]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.serde_urlencoded]]
version = "0.7.1"
criteria = "safe-to-deploy"

[[exemptions.serde_with]]
version = "3.10.0"
criteria = "safe-to-deploy"

[[exemptions.serde_with_macros]]
version = "3.10.0"
criteria = "safe-to-deploy"

[[exemptions.serialize-to-javascript]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.serialize-to-javascript-impl]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.server_fn]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.server_fn_macro]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.server_fn_macro_default]]
version = "0.6.15"
criteria = "safe-to-deploy"

[[exemptions.shlex]]
version = "1.3.0"
criteria = "safe-to-deploy"

[[exemptions.simdutf8]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.slotmap]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.soup3]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.soup3-sys]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.stable_deref_trait]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.string_cache]]
version = "0.8.7"
criteria = "safe-to-deploy"

[[exemptions.string_cache_codegen]]
version = "0.5.2"
criteria = "safe-to-deploy"

[[exemptions.swift-rs]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.syn_derive]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.sync_wrapper]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.system-deps]]
version = "6.2.2"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.13.0"
criteria = "safe-to-deploy"

[[exemptions.tendril]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.thaw]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.thaw_components]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.thaw_utils]]
version = "0.0.6"
criteria = "safe-to-deploy"

[[exemptions.thin-slice]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tiff]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.time]]
version = "0.3.36"
criteria = "safe-to-deploy"

[[exemptions.tower-service]]
version = "0.3.3"
criteria = "safe-to-deploy"

[[exemptions.typed-builder]]
version = "0.18.2"
criteria = "safe-to-deploy"

[[exemptions.typed-builder-macro]]
version = "0.18.2"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.unic-char-property]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unic-char-range]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unic-common]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unic-ucd-ident]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.urlpattern]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.utf-8]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.utf8-width]]
version = "0.1.7"
criteria = "safe-to-deploy"

[[exemptions.utf8parse]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.10.0"
criteria = "safe-to-deploy"

[[exemptions.value-bag]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.version-compare]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.vswhom]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.vswhom-sys]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.wasm-streams]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.webview2-com]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.webview2-com-macros]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.webview2-com-sys]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.weezl]]
version = "0.1.8"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winreg]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.x11]]
version = "2.21.0"
criteria = "safe-to-deploy"

[[exemptions.x11-dl]]
version = "2.21.0"
criteria = "safe-to-deploy"

[[exemptions.x11rb]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.x11rb-protocol]]
version = "0.13.1"
criteria = "safe-to-deploy"

[[exemptions.xxhash-rust]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.yansi]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"

[[exemptions.zip]]
version = "2.2.0"
criteria = "safe-to-deploy"
